# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'ui.main_window',
        'core.engine',
        'core.manager',
        'core.parser',
        'services.exchange_service',
        'services.market_data',
        'services.notifier',
        'utils.config',
        'utils.settings_manager',
        'utils.config_backup',
        'utils.translations',
        'utils.helpers',
        'utils.logger',
        'utils.resilience.circuit_breaker',
        'utils.resilience.retry_service',
        'utils.resilience.health_monitor',
        'utils.resilience.state_recovery',
        'utils.resilience.backup_manager',
        'utils.resilience.error_handler',
        'utils.resilience.decorators',
        'utils.resilience.__init__',
        'models.data_classes',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='MiBotTrading',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
